---
- name: Deploy Tomcat Application
  hosts: localhost
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "souravchandra18/tomcat-app"
        tag: latest
        source: pull

    - name: Start Docker Container
      docker_container:
        name: tomcat-app
        image: "souravchandra18/tomcat-app:latest"
        ports:
          - "8081:8081"

    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/deployment.yml') }}"

    - name: Deploy Kubernetes Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/service.yml') }}"
